// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lzucushzhrgqarkxqaxs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx6dWN1c2h6aHJncWFya3hxYXhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk0MDQzNjgsImV4cCI6MjA1NDk4MDM2OH0.LzC1JYoApyz3VYlpb3aRr_CQq3GQMtGS3yu2uj8CfhA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);